version: '2'
services:
  build:
    image: 'clux/muslrust:stable'
    command:
      - cargo
      - build
      - '--release'
    volumes:
      - '.:/volume'
    environment:
      HOME: /volume
  clean:
    image: 'clux/muslrust:stable'
    command:
      - cargo
      - clean
    volumes:
      - '.:/volume'
    environment:
      HOME: /volume
