FROM guangie88/rust:1.29.1

WORKDIR /app
COPY ./Cargo.toml ./Cargo.lock ./rustfmt.toml ./

RUN set -x \
    && cargo fetch --locked -v

COPY ./src/ ./src/

RUN cargo clippy --all \
    && cargo test --all --no-run
